name: Update

on:
  push:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      actions: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run
      run: |
        python run.py > /dev/null 2>&1

    - name: Commit
      run: |
        git config --local user.email "141336+nisc@users.noreply.github.com"
        git config --local user.name "nisc"

        git checkout --orphan temp-branch
        git add .
        git commit -m "Initial commit"
        git branch -D main
        git branch -m main
        git push --force origin main
